# Generated by Django 4.1.6 on 2023-02-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_alter_movie_added_by"),
        ("users", "0002_movieorder_user_moviesmany"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="moviesMany",
        ),
        migrations.AddField(
            model_name="user",
            name="movies_orders",
            field=models.ManyToManyField(
                related_name="users_orders",
                through="users.MovieOrder",
                to="movies.movie",
            ),
        ),
    ]
