# Generated by Django 4.1.6 on 2023-02-27 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_moviesmany_user_movies_orders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieorder",
            old_name="movies",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="movieorder",
            old_name="users",
            new_name="user",
        ),
    ]
