# Generated by Django 4.1.6 on 2023-02-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_rename_added_by_movie_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="added_by",
            field=models.EmailField(default=None, max_length=127),
        ),
    ]
