# Generated by Django 4.1.6 on 2023-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_alter_movie_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="added_by",
            field=models.EmailField(default="", max_length=127, null=True),
        ),
    ]
